//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PutniNalozi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class putni_naloziEntities : DbContext
    {
        public putni_naloziEntities()
            : base("name=putni_naloziEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Osobe> Osobe { get; set; }
        public DbSet<Prometne_dozvole> Prometne_dozvole { get; set; }
        public DbSet<Putni_nalozi> Putni_nalozi { get; set; }
        public DbSet<Putni_racun> Putni_racun { get; set; }
        public DbSet<Tehnicki_pregled> Tehnicki_pregled { get; set; }
        public DbSet<Vozacke_dozvole> Vozacke_dozvole { get; set; }
        public DbSet<Vozila> Vozila { get; set; }
    }
}
