//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PutniNalozi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Osobe
    {
        public Osobe()
        {
            this.Putni_nalozi = new HashSet<Putni_nalozi>();
            this.Vozacke_dozvole = new HashSet<Vozacke_dozvole>();
        }
    
        public int idOsobe { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string oib { get; set; }
        public System.DateTime rodjenje_datum { get; set; }
        public string rodjenje_mjesto { get; set; }
        public string prebivaliste_adresa { get; set; }
        public string prebivaliste_mjesto { get; set; }
    
        public virtual ICollection<Putni_nalozi> Putni_nalozi { get; set; }
        public virtual ICollection<Vozacke_dozvole> Vozacke_dozvole { get; set; }
    }
}
