//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PutniNalozi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prometne_dozvole
    {
        public Prometne_dozvole()
        {
            this.Tehnicki_pregled = new HashSet<Tehnicki_pregled>();
            this.Vozila = new HashSet<Vozila>();
        }
    
        public int idPrometne { get; set; }
        public Nullable<int> broj_dozvole { get; set; }
        public Nullable<int> registracija { get; set; }
        public Nullable<int> datum_registracije { get; set; }
        public Nullable<int> dozvolu_izdao { get; set; }
    
        public virtual ICollection<Tehnicki_pregled> Tehnicki_pregled { get; set; }
        public virtual ICollection<Vozila> Vozila { get; set; }
    }
}
