//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PutniNalozi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Putni_racun
    {
        public int idPutni_racun { get; set; }
        public int Putni_nalozi_idPutni_nalozi { get; set; }
        public Nullable<System.DateTime> vrijeme_dolaska { get; set; }
        public Nullable<System.DateTime> vrijeme_dolaska_2 { get; set; }
        public Nullable<double> trosak_puta { get; set; }
        public string racuni_gorivo { get; set; }
        public string racuni_ostalo { get; set; }
        public Nullable<int> prijedjeno_kilometara { get; set; }
        public Nullable<int> potroseno_goriva { get; set; }
    
        public virtual Putni_nalozi Putni_nalozi { get; set; }
    }
}
