//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PutniNalozi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tehnicki_pregled
    {
        public int idTehnicki_pregled { get; set; }
        public int Prometne_dozvole_idPrometne { get; set; }
        public System.DateTime vrijedi_od { get; set; }
        public System.DateTime vrijedi_do { get; set; }
    
        public virtual Prometne_dozvole Prometne_dozvole { get; set; }
    }
}
