//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PutniNalozi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vozacke_dozvole
    {
        public Vozacke_dozvole()
        {
            this.Osobe = new HashSet<Osobe>();
        }
    
        public int idVozacke_dozvole { get; set; }
        public Nullable<int> broj_vozacke { get; set; }
        public Nullable<int> broj_registra { get; set; }
        public Nullable<int> izdao { get; set; }
        public Nullable<int> datum_izdavanja { get; set; }
        public Nullable<int> vriejdi_do { get; set; }
        public Nullable<bool> A1 { get; set; }
        public Nullable<bool> A2 { get; set; }
        public Nullable<bool> A { get; set; }
        public Nullable<bool> B { get; set; }
        public Nullable<bool> BE { get; set; }
        public Nullable<bool> C1 { get; set; }
        public Nullable<bool> C1E { get; set; }
        public Nullable<bool> C { get; set; }
        public Nullable<bool> CE { get; set; }
        public Nullable<bool> D { get; set; }
        public Nullable<bool> DE { get; set; }
        public Nullable<bool> F { get; set; }
        public Nullable<bool> G { get; set; }
        public Nullable<bool> H { get; set; }
        public Nullable<bool> M { get; set; }
        public string napomena { get; set; }
    
        public virtual ICollection<Osobe> Osobe { get; set; }
    }
}
