//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PutniNalozi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vozila
    {
        public Vozila()
        {
            this.Putni_nalozi = new HashSet<Putni_nalozi>();
            this.Prometne_dozvole = new HashSet<Prometne_dozvole>();
        }
    
        public int idVozila { get; set; }
        public string ime_vlasnika { get; set; }
        public string adresa_vlasnika { get; set; }
        public string vrsta_vozila { get; set; }
        public string marka_vozila { get; set; }
        public string tip_vozila { get; set; }
        public string model_vozila { get; set; }
        public string boja_vozila { get; set; }
        public string broj_sasije { get; set; }
        public string oblik_karoserija { get; set; }
        public string osnovna_namjena { get; set; }
        public string proizvodjac { get; set; }
        public string drzava_podrjetla { get; set; }
        public string godina_proizvodnje { get; set; }
        public Nullable<System.DateTime> datum_prve_registracije { get; set; }
        public Nullable<int> mjesta_za_sjedenje { get; set; }
        public Nullable<int> mjesta_za_stajanje { get; set; }
        public Nullable<int> mjesta_za_lezanje { get; set; }
        public Nullable<int> dopustena_nosivost { get; set; }
        public Nullable<int> masa_praznog_vozila { get; set; }
        public Nullable<int> najvece_dopustena_masa { get; set; }
        public Nullable<int> maksimalna_brzina { get; set; }
        public Nullable<int> broj_osovina { get; set; }
        public Nullable<int> broj_pogonskih_osovina { get; set; }
        public string vrsta_motora { get; set; }
        public Nullable<int> snaga_motora { get; set; }
        public Nullable<int> broj_okretaja { get; set; }
        public Nullable<int> radni_obujam { get; set; }
        public Nullable<int> mjere_duzina { get; set; }
        public Nullable<int> mjere_sirina { get; set; }
        public Nullable<int> mjere_obujam { get; set; }
        public Nullable<int> broj_kotaca { get; set; }
        public string gume_prednje { get; set; }
        public string gume_srednje { get; set; }
        public string gume_straznje { get; set; }
        public string vrsta_kocnica { get; set; }
        public Nullable<bool> koka { get; set; }
        public Nullable<bool> vitlo { get; set; }
    
        public virtual ICollection<Putni_nalozi> Putni_nalozi { get; set; }
        public virtual ICollection<Prometne_dozvole> Prometne_dozvole { get; set; }
    }
}
